install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-beta-i686-pc-windows-gnu.exe'
  - rust-beta-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build: none

test_script:
  - cargo build --release
  - cmd: 7z a enforcer.zip target/release/enforcer.exe
  - cargo test --verbose

artifacts:
  - path: enforcer.zip
    name: Enforcer

deploy:
  description: 'windows build'
  provider: GitHub
  auth_token:
    secure: N4GrYfvlyx33sighQh9einBAFVoiXAnIhvIEfoj75UH+MH5sFNvp49BNF+ysN+Dw
  artifact: enforcer.zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
